import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home({count}) {
  const [short_url, set_short_url] = useState("")
  const [current_url, set_current_url] = useState('')
  let data = {}


  const handleOnChange = async (e) => {
    const { name, value } = e.target;
    data[name] = value
  }

  const handleOnSubmit = async () => {
    console.log(data.main_url);
    if (data.main_url) {
      const result = await axios.post("https://short-url.ataur.dev/short", data)
      set_short_url(result.data.result.short_link_id);
      set_current_url(window.location.origin)
    } else {
      alert("Link required")
    }
  }




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />


      <div className="container-g" style={{ minHeight: "90vh", marginTop: "10vh" }}>
        <h1 className={styles.title}>
          Welcome to LINK<span>SHORTNER!</span>
        </h1>

        <p className={styles.description}>
          Get started by typing/pasting{' '}
          <code className={styles.code}>your link below</code>
        </p>


        {/* search box */}
        <div className={styles.searchBox}>
          <input name="main_url" type="text" placeholder='Paste your link here ( Must include http:// or https:// )' onChange={handleOnChange} />
          <button onClick={handleOnSubmit}>Short</button>
        </div>


        {/* result section  */}
        {
          short_url && <div className={`container-g ${styles.result}`}>
            <h3>Here is short form of your link ✔ </h3>

            <pre>
              {/* in this code tag you can use variable */}
              <code>{`${current_url}/${short_url}`}</code>


              <button id="copyButton" onClick={() => {
                //pass same variable like code tage in writeText(__)
                navigator.clipboard.writeText(`${current_url}/${short_url}`);
                let copyButtonActions = document.getElementById("copyButton");
                // for better ux
                copyButtonActions.innerText = "Copied";
                copyButtonActions.style.backgroundColor = "#61e682";
                copyButtonActions.style.color = "white";

                setTimeout(() => {
                  copyButtonActions.innerText = "Copy";
                  copyButtonActions.style.backgroundColor = "#eee";
                  copyButtonActions.style.color = "gray";
                }, 5000);
              }}>Copy</button>

            </pre>
          </div>
        }
      </div>



      <footer className={styles.footer}>
       total visitor - {count}
      </footer>
    </div>
  )
}
